from enum import Enum


class CallState(str, Enum):
    RECEIVED = "RECEIVED"
    PREPROCESSING = "PREPROCESSING"
    TRANSCRIBING = "TRANSCRIBING"
    DIARIZING = "DIARIZING"
    ALIGNING = "ALIGNING"
    TAGGING = "TAGGING"
    TRANSCRIPT_READY = "TRANSCRIPT_READY"
    INSIGHT_PROCESSING = "INSIGHT_PROCESSING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"

class BatchState(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    VALIDATED = "VALIDATED"
    FAILED = "FAILED"

class WorkflowState(str, Enum):
    SUBMITTED = "SUBMITTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
